<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Promise Demo</title>
</head>
<body>

<p id="progress-p">Loading... please wait.</p>

<script src="js/jquery-2.2.4.js"></script>
</body>
<script>
  (async function () {
    "use strict";

    // let myPromise = fetch('data/inventory.json');
    // check promise state in a while loop <--- BAD solution

    // fetch('data/inventory.json').then((result) => {
    //   // console.log(result);
    //   console.log("in FIRST then()");
    //   // throw 'myException 1';
    //   return result.json();
    // }).then((jsonData) => {
    //   console.log("in SECOND then()");
    //   // throw 'myException 2';
    //   console.log(jsonData);
    //   // if this returned a promise
    // }).catch((error) => {
    //   console.log('ERROR: ' + error);
    // });

    // let myInventory = await fetchInventory();
    // console.log(myInventory);
    //
    // function fetchInventory() {
    //   return fetch('data/inventory.json').then((result) => {
    //     // console.log(result);
    //     // console.log("in FIRST then()");
    //     // throw 'myException 1';
    //     return result.json();
    //   }).then((jsonData) => {
    //     // console.log("in SECOND then()");
    //     // throw 'myException 2';
    //     // console.log(jsonData);
    //     return jsonData; // promises successful. return the data
    //   }).catch((error) => {
    //     console.log('ERROR: ' + error);
    //     return error;
    //   });
    // }

    $("#progress-p").html("Loading... please wait.");
    const myPromise = new Promise((resolve, reject) => {
      // go talk a database somewhere
      // or call an api
      setTimeout(() => {
        if (Math.random() > 0.5) {
          resolve('success');
        } else {
          reject('failure');
        }
      }, 1500);
    });

    console.log(myPromise);
    myPromise.then((result) => {
      // console.log("SUCCESS: " + result);
      // console.log(myPromise);
      $("#progress-p").html("Done: " + result);
    });
    myPromise.catch((error) => {
      console.log("ERROR: " + error);
    });

    console.log("end of script");
  })();

</script>
</html>